### PR TITLE
Line wrapping

### PR DESCRIPTION
**Pull request by jcubic**
Please review the code, it's right now wrapping by breaking the word, next I will write option to break on whitespace. This will solve issue #21

### CODE REVIEW

**Comment by patorjk** [comment]
Thank you for taking the time to work on this. It looks pretty good, I've been playing around with it and don't see any problems so far. I'd remove the console statement and add a test or two (if you're not familiar with the test setup I can add one in), but other than that I think this is good. Are you planning on submitting the whitespaceBreak option as a separate PR or as part of this one?

**Comment by jcubic** [comment]
I think I will add that option here.

**Comment by jcubic** [comment]
I've added the code for word break it's little bit more complex, but it works and added unit tests.

**Comment by jcubic** [comment]
There is also need to update README with new options.

**Comment by patorjk** [comment]
Nicely done, thanks for the PR! I'll update the README and work on a release later tonight.

**Comment by patorjk** [comment]
Hmm, actually after testing this further I think there was a bug in the whitespaceBreak feature. I noticed that in some cases it wasn't respecting the width parameter. I made some small tweaks and have it so that lines stay under the width parameter. Would you mind just checking to make sure the edits I made make sense? I believe everything is working correctly but just want another set of eyes on it.

I've updated the examples/font-end/index.htm file to make testing a little easier.

http://localhost/figlet/examples/front-end/index.htm

**Comment by jcubic** [comment]
I'm not sure if this what you've found but there will be another issue when word is bigger the the width it need to be broken into two lines even that there are no whitespace.

The change look weird, did fix some use case? I will explain how maxWIdth works

in your code:

you have width of 10

["foo", " ", "bar"]

this is 6 len and next word is "fantastic" for each iteration of that word it will check the same "foo bar" array. but it need to check each next letter if combined with current line is larger the the width.

so the line is 

"foo bar "

it will check "foo bar f", "foo bar fa" and when it check "foo bar fan" it will be 11 so it will be larger then 10 and it will break using word array "foo bar" will be next line.

PS: why did you comment out one unit tests? Because the tests don't pass? If you have tests that break with my code you can add that test into repo or here and will try to fix my code so it pass.

**Comment by patorjk** [comment]
@jcubic I commented the test out since it started failing since it's output was different than mine after I made the tweaks. In the front-end/index.htm file I put in some markers to mark how long the the generated text was and noticed that the generated output would occasionally go beyond the character limit when whitespaceBreak was used (when only the width option was used, everything worked perfectly).

For example, if width was set to "80" and whitespaceBreak was true, the output would sometimes go beyond 80 characters in width. With the tweaks I made everything stays below the limit, however, I'm not sure it's optimal, I just haven't had time the past few days to revisit. If you want to take a look it'd be appreciated. Also, I think this is a really cool feature and appreciate you putting the time into this - this will get deployed later this month, it just needs some tweaks and/or some additional testing to make sure all the kinks are ironed out.

**Comment by jcubic** [comment]
Will check it, didn't test actual length of the output text. Maybe there should be unit test that create bunch of texts and only test the length of the max line.

**Comment by jcubic** [comment]
I can create PR but probably there will be conflicts you my code, I can just delete your last changes and make better fix, will also double check your solution.

**Pull request merged**
