### PR TITLE
Add Pagga font

### PR DESCRIPTION
**Pull request by Horhik**
I found this amazing font by Sam Hocevar in [toilet](https://github.com/cacalabs/toilet) and made this font importable to js.
image

### CODE REVIEW

**Comment by patorjk** [comment]
I wouldn't mind adding the Pagga font, however, I'm not sure what that last commit is for. Why are all of the fonts updated? Also, I don't want the spacing changed from 4 to 2 spaces.

**Comment by Horhik** [comment]
Ok, this problem with spaces was accidentally due to `prettier` and "save all"

**Comment by patorjk** [comment]
Sorry, I missed that this was updated. I'll add this into the next release (should probably be within the next week).

**Comment by Horhik** [comment]
Thanks!

**Pull request merged**
