### PR TITLE
fixing line wrapping

### PR DESCRIPTION
**Pull request by jcubic**
The algorithm for line wrapping got updated and unit tests got fixes there is also check that the line are no more then 80 characters.

Fixes for #57 that better implement #21.

### CODE REVIEW

**Comment by jcubic** [comment]
Also I'm not sure if I've done calculation right right now the len of each line in normal wrap is 79 when option is 80 I think it should be 80.

**Comment by jcubic** [comment]
I think it's correct it will just not fit another fig character. The line should not be exactly the same length as width.

**Comment by patorjk** [comment]
Sorry, I missed the email for this. Thank you for putting this together! Just tried it out - it looks really good. Only issue I noticed was that long strings don't break "1234567890", however, I think if the whitespaceBreak is true this makes sense, since we're saying breaks will happen on whitespaces. I'll just make a note in the README for that option that overflow is possible and to just the width parameter if a strict text width needs to be followed.

I'm going to wait a day or so before merging in, but I hope to have this out soon. Thank you again for taking this on.

**Comment by jcubic** [comment]
Yes, I forget about long words they should break on the character if space not found, will try to create another PR with fix for that as well.

**Comment by jcubic** [comment]
I think I've fixed the issue, it now break words if they are longer then the width. I will also create unit tests for this.

You can test manually if it work correctly.

**Comment by patorjk** [comment]
This doesn't seem to work. I have the following setup on my box to try out the PR: (figwrap being the directory of your branch)

http://localhost/figwrap/examples/front-end/index.htm

If I type:

"see if"

The output is as if I typed "seeif". However, if I type:

"see if "

It outputs as if I typed "see if".

Similarly, typing "aaaaaaaaaa" results in output that doesn't break.

**Comment by jcubic** [comment]
Fixed breaking last line + unit test. There is one thing, with code:
```
    figWords.push({fig: textFigLine, overlap: 1});
```

it's when word was broken into two lines and the overlap is for flast word I think it's fine to have 1 as overlap with this case, is it safe default? I think it will only happen for last broken word:

example:
```
LongLongLongWord, width 30

overlap: 1 will be for Word in single line.
```
I'm not sure if there is any edge case when this will break the code.

**Comment by jcubic** [comment]
@patorjk about your comment just read it now, there was issue with last word in line and I double spaces. It's fixed now. Also added unit test with `xxxxxxxxxxxxxxxxxxxxxxxx` and width 30 + whitespace break.

**Comment by patorjk** [comment]
Just checked this out and this looks pretty good so far. I'll loop back tomorrow and try it out some more but I think we may now be good to go.

**Pull request merged**
